version: '3.8'

services:
  app:
    build: 
        dockerfile: Dockerfile-dev
        context: .
    ports:
    - 8080:80
    volumes:
    - .:/var/www/html
    depends_on:
    - mysql
  mysql:
    image: docker.io/mariadb:10.3
    volumes:
    - db:/var/lib/mysql
    - ./mysql/dumpfile_location/file.sql:/docker-entrypoint-initdb.d/file.sql # REPLACE file.sql with the name of the file you want to import.
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306

volumes:
  db: